l = [2,4,6,8,10,1,2,3,5,7,9,2]
print(len(l))
print(l.remove(1))
print(l.count(2))
print(list(reversed(l)))
print(l.reverse())
print(l)
print(l.sort())
print(l)
print(sorted(l,reverse=True))
print(l.insert(0,100))
print(l)
print(l.remove(100))
print(l)
print()
