a = "bablugoud from hyd"
print(a.center(20,'$'))
print(a.ljust(20,"%"))
print(a.rjust(20,"!"))
print(a.capitalize())
print(a.title())
print(a.swapcase())
print(a.lower())
print(a.islower())
print(a.upper())
print(a.split('u'))
print(a.lstrip("bablu"))
print(a.strip("goud"))
print(a.find("u"))
print(a.rfind("u"))#last occurance of word
print(a.replace('goud','reddy'))
print(min(a))
print(max(a))
print(a.encode())
print(a.isidentifier())
print(a.isprintable())
print(a.isalpha())
